### ISSUE TITLE
Private Page for Content Sharing

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#4]
1. Go to: http://ipbs.org
RESULT: no page for private content sharing
NOTE: This is the same idea as the public page #3 for content sharing, except private. We’ll want to add Gravity Forms and RCP to the site to accomplish this.

EXPECT 1: create form via Gravity Forms for producers to populate content with 
EXPECT 2: create page controlled by RCP that pulls in content from form

From client:
“This concept mirrors the above. However, it is intended to be populated by producers who complete a template for posting and accessed by Underwriting Account Executives at IPBS stations. Create a private page for IPBS pros with the password which briefly describes station produced content in headline fashion. The page could be topical in nature and updated every 30 days. The page could reside at IPBS.org  (or a station’s website.)  When a topical program headline description is selected, a link takes the visitor to the station’s web archive for further detail and video. Underwriting Account Executives can construct their presentation materials from content they view.”

**Comment by benlk** [comment]
Questions:

- Whose RCP license are we using?
- Whose Gravity Forms license are we using?
- What fields will they want presented, beyond the title and a link?

Parts to this ticket:

- [x] gravity form, taking: link, title, blurb text, 
- [x] Install RCP
- [x] create page, restrict using RCP
- [x] get page to display Gravity Form entries as title, link, what else? Show last 30 days of entries, newest first. 
- [ ] docs for RCP for IPBS

**Comment by julia-smith** [comment]
Use INN's shared RCP and Gravity Forms developer licenses

**Comment by benlk** [comment]
Questions:

- How does an Underwriting Account Executive get an account, in IPBS's ideal workflow? Is the account created by IPBS for the UAE, or does the UAE request an account through the website? Does the UAE need to pay for access?

Things they'll want to take a look at:

- email notification settings: http://ipbs.staging.wpengine.com/wp-admin/admin.php?page=rcp-settings#emails
- subscription levels: http://ipbs.staging.wpengine.com/wp-admin/admin.php?page=rcp-member-levels
- the private form: http://ipbs.staging.wpengine.com/?page_id=342
- the page which is fed by the form: http://ipbs.staging.wpengine.com/?page_id=345
- internal styles on pages, because I think the right sidebar is covering stuff up in the main column.

**Comment by kaylima** [comment]
> How does an Underwriting Account Executive get an account, in IPBS's ideal workflow? Is the account created by IPBS for the UAE, or does the UAE request an account through the website? Does the UAE need to pay for access?

"I think that IPBS could create the account for EAE if the instructions are simple and clearly written down. There is no payments involved."

**Comment by benlk** [comment]
For this, should the "IPBS Member sign-in page" button on the homepage go to the RCP login page?

For logged-in members, should there be a notice somewhere (anywhere) about the location of the private form and/or the location of the private form's listed posts? If we're using the `[login_form]` shortcode, [there's a parameter](http://docs.restrictcontentpro.com/article/1598-loginform) that can be set to automatically send users to one of those pages after logging in, but they'll probably want a visible link somewhere.

Here's docs on how IPBS should create accounts for EAEs: http://docs.restrictcontentpro.com/article/1705-how-to-manually-add-a-new-member
