### ISSUE TITLE
Interior page template setup

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#41]
Note two column-ish design that needs to be set up as discussed for left-align blocks

[interior-desktop.pdf](https://github.com/INN/umbrella-ipbs/files/4068581/interior-desktop.pdf)

**Comment by benlk** [comment]
I'd increase this to 4h, because of the complexity of making sure that all content has the appropriate widths and positioning on the page.

**Comment by benlk** [comment]
Is the template with the left-aligned block column supposed to replace the single-column template, or is this supposed to be a separate template from the default Largo single-column template, two-column template with sidebar, and blank fullwidth template?

**Comment by MirandaEcho** [comment]
@benlk good question. We also have this new job board layout, which doesn't have the columns. Given that, what do you recommend?
![jobs-board-2 (1)](https://user-images.githubusercontent.com/48263361/73406965-6b058f00-42bd-11ea-8dbd-7257481c7034.png)

**Comment by benlk** [comment]
Job board would be its own thing, I think. This is mostly a question of whether we attempt to override Largo's single-column post styles or create a new template which would be the default post template for IPBS.

**Comment by benlk** [comment]
New template.

**Comment by benlk** [comment]
![Screen Shot 2020-01-31 at 17 05 30](https://user-images.githubusercontent.com/1754187/73577805-eac16400-444b-11ea-850d-b5285f11824d.png)

- [x] make group block left-alignable
- [x] template file for this single column offset to the right
- [ ] get this template to show up as an option for the default picker via a filter on largo_options
- [ ] styles to make the layout

See also generally https://github.com/INN/largo/issues/1847

**Comment by benlk** [comment]
This is annoying:

https://github.com/INN/largo/blob/c41d8519370b48a6e53ce36b3b516d3e54e39d66/inc/post-metaboxes.php#L174-L181

According to the metabox that displays the dropdown for choosing the post template, the Default option is the one-column standard template, or if not that, then it must be the two-column template. Though the Default may be something else, if it's something else, then the Default is labeled as the two-column template.

The quick solution is to replace the meta box and name the default "Sitewide default."

The longer solution is to make that default grab the label from the theme options (requiring searching the array of options because none of the individual arrays in the array of options have a key named in the options array)

There's a third level of difficulty in here somewhere, where we keep the existing template stuff but make sure it uses the filenames of the templates rather than custom IDs, like how the `_wp_post_template` option stores the template name.

Fourth level is https://github.com/INN/largo/issues/1847

Also, https://github.com/INN/largo/blob/trunk/single.php will need to change to pull the right template.

**Comment by benlk** [comment]
Template-creation work done; next up is the actual styling.

**Comment by benlk** [comment]
![image](https://user-images.githubusercontent.com/1754187/73687382-e5f0f000-4697-11ea-9d0d-f62efa4d87bd.png)

A lovely bug: if the left-aligned block is taller than the next block, it pushes the second-next block down onto a new row.

This might be solved by one of the grid-auto-* properties.

**Comment by benlk** [comment]
I need to stop working on this layout, because I have run out of time and also hit the "CSS was a mistake" point.

![Screenshot_2020-02-03 #41 test double-column template](https://user-images.githubusercontent.com/1754187/73691265-08870700-46a0-11ea-9fba-d9e409875da4.png)

Tried:
- Using CSS grid-column to specify where chunks of layout start and stop. This doesn't work because there's no way to get blocks to automatically span rows, causing the big white space seen in https://github.com/INN/umbrella-ipbs/issues/41#issuecomment-581599136
- Using a left positioning offset to move everything save `.alignwide` and `.alignfull` and `.alignleft` to the right, then defining the width of `.alignleft` to be the left positioning. Having `float: left` on `.alignleft` causes the gaps in paragraphs seen in the screenshot at the top of this comment; not having it causes different problems.

So what's left, and what works in testing so far:
- pad `#entry-content` and use negative left margins to get everything to line up again.

829964d is 90% of the way there; the only remaining layout problem is `.alignfull` not being correctly aligned above 1170px, which I think is because I lost a `2.5vw` or a `@measure` somewhere in the math.

<img width="511" alt="Screen Shot 2020-02-03 at 16 30 21" src="https://user-images.githubusercontent.com/1754187/73692557-8c41f300-46a2-11ea-8cb4-aa6988fca795.png">

**Comment by benlk** [comment]
#77 has been merged, so unless we're putting QA in here, I think this is completed.
