### ISSUE TITLE
Homepage: Events section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#42]
- install Tockify plugin
- styling
- link to Google Calendar (TBD)

<img width="1236" alt="Screen Shot 2020-01-15 at 6 42 01 PM" src="https://user-images.githubusercontent.com/48263361/72483513-e0a23300-37c6-11ea-91dc-931bd20b452d.png">

**Comment by joshdarby** [comment]
I would think 4 hours for this one since we've never used it before and I'm not sure what limitations or weirdness we'll run into when setting it up and styling it.

**Comment by benlk** [comment]
Do we have a Tockify license that we'll be using here, or does the site come with one?

**Comment by joshdarby** [comment]
So, after fighting with Tockify for a couple of hours, I'm not sure how close to the design we can get with this. Their plugin doesn't actually do anything useful except for creating a shortcode that pulls in an iframe of events from your calendar. 

Since it's an iframe coming from tockify's domain, we can't modify any of the css for the elements in the iframe (events).

However, Tockify has an "ok" calendar customizer that lets you modify how the iframe presents events, but it doesn't give a ton of options. For example, it doesn't let you modify how many events show per row or break them into separate columns.

Noting that, here's the best I could do so far 😅 :
![Screen Shot 2020-01-23 at 3 26 22 PM](https://user-images.githubusercontent.com/18353636/73021359-6d677500-3df5-11ea-90da-bfcbffb2d938.png)

**Comment by joshdarby** [comment]
So, instead of Tockify, we could use the [Simple Calendar](https://simplecalendar.io/) plugin. It pulls in Google Calendar events via API instead of how Tockify creates an iframe for their calendar and then makes you embed it.

The only downside to not using Tockify is that you can't set tags or images for Google cal events, so we wouldn't be able to include either of those for events if we use the Google Calendar way 😕 

However, the Simple Calendar plugin does allow us to set up the calendar in a way that will be pretty easy (hopefully) for us to match the styling of the designs. Here's how it is out of the box:
![Screen Shot 2020-01-27 at 2 47 34 PM](https://user-images.githubusercontent.com/18353636/73208425-6fdb0f00-4114-11ea-8493-5959ce8b617c.png)
 
@MirandaEcho Are we ok with not having images and tags for each event or should I keep searching?

**Comment by MirandaEcho** [comment]
@joshdarby - lets proceed without images or tags. Thanks!
