### ISSUE TITLE
Homepage: Member Stations text and map embed

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#57]
<img width="865" alt="Screen Shot 2020-01-23 at 6 12 53 PM" src="https://user-images.githubusercontent.com/48263361/73034909-fb4e5a80-3e0b-11ea-9c99-78e1e71a3912.png">

**Comment by benlk** [comment]
Are we making any changes to the existing member station map?

If not, then this is some css and some js that need to be enqueued alongside the existing SVG, all of it already written in the `ipbs` non-Largo-child theme: **2h**, to include setting up a very boring zero-configuration widget that can be plopped into place on the homepage or other places. (Widget because this needs to have the JS/CSS enqueued for the SVG to be styled appropriately, and a widget is the best way to make sure that gets enqueued.)

**Comment by benlk** [comment]
Proceeding with SVG as it exists for now.
