### ISSUE TITLE
Homepage: Features section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#59]
![Screen Shot 2020-01-23 at 6 14 46 PM](https://user-images.githubusercontent.com/48263361/73034991-3f415f80-3e0c-11ea-9ab5-1f6082ea037e.png)

**Comment by benlk** [comment]
See note in #56 about whether this might be a Largo Recent posts widget, but if it is: **4h** because of the more-complex blue background item behind the grid layout. I'm assuming the Button is a link to continue reading the article, and that these are all posts on the site within a "features" category.

**Comment by benlk** [comment]
Wrinkle in this design: the Largo Recent Posts widget doesn't have the "more" link present in its output options:
![Screen Shot 2020-01-27 at 11 41 19](https://user-images.githubusercontent.com/1754187/73196036-e835d600-40fc-11ea-9fd8-4d655e8c2dab.png)

Should we add that "read more" link to `partials/widget-content.php`?
