### ISSUE TITLE
Inline link styles

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#64]
<img width="781" alt="Screen Shot 2020-01-23 at 6 29 04 PM" src="https://user-images.githubusercontent.com/48263361/73035587-3c476e80-3e0e-11ea-84c2-ae50fb814ce9.png">

**Comment by benlk** [comment]
Is this just within posts, or elsewhere as well? Is the underline's offset supposed to move when hovered, or is that just a glitch in the mockup? Moving underlines like that add complexity. 

- Red and underlined when not hovered
- Black and underlined when hovered

On the assumption that the underline does not move, and we're using the plain `text-decoration: underline;`: might roll this in with #62, but otherwise it's 1h.

**Comment by benlk** [comment]
No custom underline; roll this into #62.

**Comment by MirandaEcho** [comment]
Combined with 62, closing.
